global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'python_app'
    metrics_path: '/api/v1/metrics'  # Указываем новый путь для метрик
    static_configs:
      - targets: ['app:8000']  # Имя сервиса из docker-compose.yml
