[app_settings]
app_port = 8000
app_version = "1.0.0"
app_name = "pay_service"
app_host = "0.0.0.0"
app_mount = "/api/v1"


[db_settings]
db_name = "postgres"
db_user = "myuser"
db_password = "mypassword"
db_host = "db"
db_port = 5432
